FROM continuumio/miniconda3:latest

ENV PYTHONUNBUFFERED=1

WORKDIR /app
SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get -y install \
    gcc \
    g++ \
    libxrender-dev \
    libsm6 \
    libxext6

RUN mkdir /kms_env
ENV ENV_PREFIX=/kms_env
COPY environment.yml /app/
RUN conda env create --prefix $ENV_PREFIX --file environment.yml --force
RUN echo "rmg==3.0" > /kms_env/conda-meta/pinned
