version: "3.7"

services:
  db:
    image: postgres
    env_file: .env.dev
    ports:
      - "5432:5432"
  debug:
    build: .
    tty: true
    env_file: .env.dev
    volumes:
      - .:/app
      - rmg-models:/app/rmg-models
    ports:
      - "5678:5678"
      - "8080:8080"
    depends_on:
      - db

volumes:
  rmg-models:
    external: true
