# Generated by Django 2.2.5 on 2020-03-30 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20191126_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='firstname',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='author',
            name='lastname',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='thermo',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Species'),
        ),
    ]
