# Generated by Django 3.0.3 on 2020-04-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200330_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={},
        ),
    ]
