# Generated by Django 3.0.3 on 2020-04-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200408_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('bPrimeID',)},
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('publicationYear', 'sourceTitle')},
        ),
    ]
