# Generated by Django 3.0.3 on 2020-04-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200408_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
