# Generated by Django 3.0.3 on 2020-04-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20200408_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='sourceTitle',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
