# Generated by Django 3.0.3 on 2020-04-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20200408_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='journalName',
            field=models.CharField(blank=True, max_length=300, verbose_name='Journal Name'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Model Name in Importer'),
        ),
        migrations.AlterField(
            model_name='source',
            name='pageNumbers',
            field=models.CharField(blank=True, help_text='[page #]-[page #]', max_length=100, verbose_name='Page Numbers'),
        ),
        migrations.AlterField(
            model_name='source',
            name='sourceTitle',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Article Title'),
        ),
    ]
