# Generated by Django 3.0.3 on 2020-04-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20200420_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='rPrimeID',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PrIMe ID'),
        ),
    ]
