# Generated by Django 3.0.3 on 2020-04-29 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20200422_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basekineticsdata',
            name='kinetics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Kinetics'),
        ),
    ]
