# Generated by Django 3.0.3 on 2020-04-29 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20200429_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinetics',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Reaction'),
        ),
    ]
