# Generated by Django 3.0.3 on 2020-05-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20200429_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lindemann',
            name='alpha',
        ),
        migrations.RemoveField(
            model_name='lindemann',
            name='t1',
        ),
        migrations.RemoveField(
            model_name='lindemann',
            name='t2',
        ),
        migrations.RemoveField(
            model_name='lindemann',
            name='t3',
        ),
    ]
