# Generated by Django 3.0.3 on 2020-05-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20200504_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lindemann',
            name='high_arrhenius',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='database.Arrhenius'),
        ),
        migrations.AlterField(
            model_name='lindemann',
            name='low_arrhenius',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='database.Arrhenius'),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='arrhenius',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Arrhenius'),
        ),
        migrations.AlterField(
            model_name='thirdbody',
            name='low_arrhenius',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Arrhenius'),
        ),
        migrations.AlterField(
            model_name='troe',
            name='high_arrhenius',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='database.Arrhenius'),
        ),
        migrations.AlterField(
            model_name='troe',
            name='low_arrhenius',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='database.Arrhenius'),
        ),
    ]
