# Generated by Django 3.0.3 on 2020-07-11 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20200701_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='search_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='species',
            name='search_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True),
        ),
    ]
