# Generated by Django 3.0.3 on 2020-07-17 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20200701_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basekineticsdata',
            name='kinetics',
        ),
        migrations.AddField(
            model_name='kinetics',
            name='data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.BaseKineticsData'),
        ),
    ]
