# Generated by Django 3.0.3 on 2020-07-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20200717_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='basekineticsdata',
            name='order',
            field=models.FloatField(blank=True, help_text='Overall reaction order', null=True),
        ),
    ]
