# Generated by Django 3.0.3 on 2020-07-24 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20200722_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrhenius',
            options={},
        ),
        migrations.RenameField(
            model_name='kinetics',
            old_name='data',
            new_name='base_data',
        ),
    ]
