# Generated by Django 3.0.3 on 2020-07-11 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20200711_1858'),
    ]
    def add_uuids(apps, schema_editor):
        Species = apps.get_model("database", "Species")
        Reaction = apps.get_model("database", "Reaction")
        species = Species.objects.all()
        reactions = Reaction.objects.all()

        for s in species:
            s.search_id = uuid.uuid4()
            s.save()

        for r in reactions:
            r.search_id = uuid.uuid4()
            r.save()

    def remove_uuids(apps, schema_editor):
        Species = apps.get_model("database", "Species")
        Reaction = apps.get_model("database", "Reaction")
        species = Species.objects.all()
        reactions = Reaction.objects.all()

        for s in species:
            s.update(search_id=None)
            s.save()

        for r in reactions:
            r.update(search_id=None)
            r.save()



    operations = [
        migrations.RunPython(add_uuids, remove_uuids),
        migrations.AlterField(
            model_name='reaction',
            name='search_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False)
        ),
        migrations.AlterField(
            model_name='species',
            name='search_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False)
        ),
    ]
