# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import kineticmodels.models.kinetic_model
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'format: surname, firstname', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name=b'Order of authorship')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Author')),
            ],
        ),
        migrations.CreateModel(
            name='BaseKineticsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temp', models.FloatField(blank=True, help_text=b'units: K', null=True, verbose_name=b'Lower Temp Bound')),
                ('max_temp', models.FloatField(blank=True, help_text=b'units: K', null=True, verbose_name=b'Upper Temp Bound')),
                ('min_pressure', models.FloatField(blank=True, help_text=b'units: Pa', null=True, verbose_name=b'Lower Pressure Bound')),
                ('max_pressure', models.FloatField(blank=True, help_text=b'units: Pa', null=True, verbose_name=b'Upper Pressure Bound')),
            ],
        ),
        migrations.CreateModel(
            name='Efficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efficiency', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Isomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inchi', models.CharField(blank=True, max_length=500, verbose_name=b'InChI')),
            ],
        ),
        migrations.CreateModel(
            name='KineticModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mPrimeID', models.CharField(blank=True, max_length=9, verbose_name=b'PrIMe ID')),
                ('modelName', models.CharField(default=uuid.uuid4, max_length=200, unique=True)),
                ('additionalInfo', models.CharField(blank=True, max_length=1000)),
                ('chemkinReactionsFile', models.FileField(upload_to=kineticmodels.models.kinetic_model.upload_chemkin_to)),
                ('chemkinThermoFile', models.FileField(upload_to=kineticmodels.models.kinetic_model.upload_thermo_to)),
                ('chemkinTransportFile', models.FileField(blank=True, upload_to=kineticmodels.models.kinetic_model.upload_transport_to)),
                ('rmgImportPath', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Kinetic Models',
            },
        ),
        migrations.CreateModel(
            name='Kinetics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rkPrimeID', models.CharField(blank=True, max_length=10)),
                ('relativeUncertainty', models.FloatField(blank=True, null=True)),
                ('isReverse', models.BooleanField(default=False, help_text=b'Is this the rate for the reverse reaction?')),
            ],
            options={
                'verbose_name_plural': 'Kinetics',
            },
        ),
        migrations.CreateModel(
            name='KineticsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('kineticModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.KineticModel')),
                ('kinetics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Kinetics')),
            ],
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rPrimeID', models.CharField(max_length=10, unique=True, verbose_name=b'PrIMe ID')),
                ('isReversible', models.BooleanField(default=True, help_text=b'Is this reaction reversible?')),
            ],
            options={
                'ordering': ('rPrimeID',),
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bPrimeID', models.CharField(blank=True, default=b'', max_length=9, verbose_name=b'Prime ID')),
                ('publicationYear', models.CharField(blank=True, default=b'', max_length=4, verbose_name=b'Year of Publication')),
                ('sourceTitle', models.CharField(blank=True, default=b'', max_length=300)),
                ('journalName', models.CharField(blank=True, max_length=300)),
                ('journalVolumeNumber', models.CharField(blank=True, max_length=10, verbose_name=b'Journal Volume Number')),
                ('pageNumbers', models.CharField(blank=True, help_text=b'[page #]-[page #]', max_length=100)),
                ('doi', models.CharField(blank=True, max_length=80)),
                ('authors', models.ManyToManyField(blank=True, through='kineticmodels.Authorship', to='kineticmodels.Author')),
            ],
            options={
                'ordering': ('bPrimeID',),
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sPrimeID', models.CharField(max_length=9, verbose_name=b'PrIMe ID')),
                ('formula', models.CharField(blank=True, max_length=50)),
                ('inchi', models.CharField(blank=True, max_length=500, verbose_name=b'InChI')),
                ('cas', models.CharField(blank=True, max_length=400, verbose_name=b'CAS Registry Number')),
            ],
            options={
                'ordering': ('sPrimeID',),
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='SpeciesName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('kineticModel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.KineticModel')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Species')),
            ],
            options={
                'verbose_name_plural': 'Alternative Species Names',
            },
        ),
        migrations.CreateModel(
            name='Stoichiometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stoichiometry', models.FloatField(default=0.0)),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Reaction')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Species')),
            ],
            options={
                'verbose_name_plural': 'Stoichiometries',
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(blank=True, max_length=500, verbose_name=b'SMILES')),
                ('adjacencyList', models.TextField(verbose_name=b'Adjacency List')),
                ('electronicState', models.IntegerField(verbose_name=b'Electronic State')),
                ('isomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Isomer')),
            ],
        ),
        migrations.CreateModel(
            name='Thermo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thpPrimeID', models.CharField(blank=True, max_length=11)),
                ('preferredKey', models.CharField(blank=True, help_text=b'i.e. T 11/97, or J 3/65', max_length=20)),
                ('referenceTemperature', models.FloatField(blank=True, default=0.0, help_text=b'units: K', verbose_name=b'Reference State Temperature')),
                ('referencePressure', models.FloatField(blank=True, default=0.0, help_text=b'units: Pa', verbose_name=b'Reference State Pressure')),
                ('dfH', models.FloatField(blank=True, default=0.0, help_text=b'units: J/mol', verbose_name=b'Enthalpy of Formation')),
                ('lowerTempBound1', models.FloatField(default=0.0, help_text=b'units: K', verbose_name=b'Polynomial 1 Lower Temp Bound')),
                ('upperTempBound1', models.FloatField(default=0.0, help_text=b'units: K', verbose_name=b'Polynomial 1 Upper Temp Bound')),
                ('coefficient11', models.FloatField(default=0.0, verbose_name=b'Polynomial 1 Coefficient 1')),
                ('coefficient21', models.FloatField(default=0.0, verbose_name=b'Polynomial 1 Coefficient 2')),
                ('coefficient31', models.FloatField(default=0.0, verbose_name=b'Polynomial 1 Coefficient 3')),
                ('coefficient41', models.FloatField(default=0.0, verbose_name=b'Polynomial 1 Coefficient 4')),
                ('coefficient51', models.FloatField(default=0.0, verbose_name=b'Polynomial 1 Coefficient 5')),
                ('coefficient61', models.FloatField(default=0.0, verbose_name=b'Polynomial 1 Coefficient 6')),
                ('coefficient71', models.FloatField(default=0.0, verbose_name=b'Polynomial 1 Coefficient 7')),
                ('lowerTempBound2', models.FloatField(default=0.0, help_text=b'units: K', verbose_name=b'Polynomial 2 Lower Temp Bound')),
                ('upperTempBound2', models.FloatField(default=0.0, help_text=b'units: K', verbose_name=b'Polynomial 2 Upper Temp Bound')),
                ('coefficient12', models.FloatField(default=0.0, verbose_name=b'Polynomial 2 Coefficient 1')),
                ('coefficient22', models.FloatField(default=0.0, verbose_name=b'Polynomial 2 Coefficient 2')),
                ('coefficient32', models.FloatField(default=0.0, verbose_name=b'Polynomial 2 Coefficient 3')),
                ('coefficient42', models.FloatField(default=0.0, verbose_name=b'Polynomial 2 Coefficient 4')),
                ('coefficient52', models.FloatField(default=0.0, verbose_name=b'Polynomial 2 Coefficient 5')),
                ('coefficient62', models.FloatField(default=0.0, verbose_name=b'Polynomial 2 Coefficient 6')),
                ('coefficient72', models.FloatField(default=0.0, verbose_name=b'Polynomial 2 Coefficient 7')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Source')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Species')),
            ],
        ),
        migrations.CreateModel(
            name='ThermoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('kineticModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.KineticModel')),
                ('thermo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Thermo')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trPrimeID', models.CharField(blank=True, max_length=10)),
                ('geometry', models.FloatField(blank=True, default=0.0)),
                ('potentialWellDepth', models.FloatField(blank=True, default=0.0, help_text=b'units: K', verbose_name=b'Potential Well Depth')),
                ('collisionDiameter', models.FloatField(blank=True, default=0.0, help_text=b'units: Angstroms', verbose_name=b'Collision Diameter')),
                ('dipoleMoment', models.FloatField(blank=True, default=0.0, help_text=b'units: Debye')),
                ('polarizability', models.FloatField(blank=True, default=0.0, help_text=b'units: cubic Angstroms')),
                ('rotationalRelaxation', models.FloatField(blank=True, default=0.0, verbose_name=b'Rotational Relaxation')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Source')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Species')),
            ],
        ),
        migrations.CreateModel(
            name='Arrhenius',
            fields=[
                ('basekineticsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kineticmodels.BaseKineticsData')),
                ('AValue', models.FloatField(default=0.0)),
                ('AValueUncertainty', models.FloatField(blank=True, null=True)),
                ('nValue', models.FloatField(default=0.0)),
                ('EValue', models.FloatField(default=0.0)),
                ('EValueUncertainty', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Arrhenius Kinetics',
            },
            bases=('kineticmodels.basekineticsdata',),
        ),
        migrations.CreateModel(
            name='ArrheniusEP',
            fields=[
                ('basekineticsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kineticmodels.BaseKineticsData')),
                ('a', models.FloatField()),
                ('n', models.FloatField()),
                ('ep_alpha', models.FloatField()),
                ('e0', models.FloatField()),
            ],
            bases=('kineticmodels.basekineticsdata',),
        ),
        migrations.CreateModel(
            name='Chebyshev',
            fields=[
                ('basekineticsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kineticmodels.BaseKineticsData')),
                ('coefficient_matrix', models.TextField()),
                ('units', models.CharField(max_length=25)),
                ('inv_temp_terms', models.IntegerField()),
                ('log_pressure_terms', models.IntegerField()),
            ],
            bases=('kineticmodels.basekineticsdata',),
        ),
        migrations.CreateModel(
            name='KineticsData',
            fields=[
                ('basekineticsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kineticmodels.BaseKineticsData')),
                ('temp_array', models.TextField()),
                ('rate_coefficients', models.TextField()),
            ],
            bases=('kineticmodels.basekineticsdata',),
        ),
        migrations.CreateModel(
            name='Lindemann',
            fields=[
                ('basekineticsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kineticmodels.BaseKineticsData')),
                ('alpha', models.FloatField()),
                ('t1', models.FloatField()),
                ('t2', models.FloatField()),
                ('t3', models.FloatField()),
                ('high_arrhenius', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_lindemann', to='kineticmodels.Arrhenius')),
                ('low_arrhenius', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_lindemann', to='kineticmodels.Arrhenius')),
            ],
            bases=('kineticmodels.basekineticsdata',),
        ),
        migrations.CreateModel(
            name='MultiArrhenius',
            fields=[
                ('basekineticsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kineticmodels.BaseKineticsData')),
                ('arrhenius_set', models.ManyToManyField(to='kineticmodels.Arrhenius')),
            ],
            bases=('kineticmodels.basekineticsdata',),
        ),
        migrations.CreateModel(
            name='MultiPDepArrhenius',
            fields=[
                ('basekineticsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kineticmodels.BaseKineticsData')),
            ],
            bases=('kineticmodels.basekineticsdata',),
        ),
        migrations.CreateModel(
            name='PDepArrhenius',
            fields=[
                ('basekineticsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kineticmodels.BaseKineticsData')),
            ],
            bases=('kineticmodels.basekineticsdata',),
        ),
        migrations.CreateModel(
            name='ThirdBody',
            fields=[
                ('basekineticsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kineticmodels.BaseKineticsData')),
                ('low_arrhenius', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Arrhenius')),
            ],
            bases=('kineticmodels.basekineticsdata',),
        ),
        migrations.AddField(
            model_name='reaction',
            name='species',
            field=models.ManyToManyField(through='kineticmodels.Stoichiometry', to='kineticmodels.Species'),
        ),
        migrations.AddField(
            model_name='kinetics',
            name='reaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Reaction'),
        ),
        migrations.AddField(
            model_name='kinetics',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Source'),
        ),
        migrations.AddField(
            model_name='kineticmodel',
            name='kinetics',
            field=models.ManyToManyField(blank=True, through='kineticmodels.KineticsComment', to='kineticmodels.Kinetics'),
        ),
        migrations.AddField(
            model_name='kineticmodel',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Source'),
        ),
        migrations.AddField(
            model_name='kineticmodel',
            name='species',
            field=models.ManyToManyField(blank=True, through='kineticmodels.SpeciesName', to='kineticmodels.Species'),
        ),
        migrations.AddField(
            model_name='kineticmodel',
            name='thermo',
            field=models.ManyToManyField(blank=True, through='kineticmodels.ThermoComment', to='kineticmodels.Thermo'),
        ),
        migrations.AddField(
            model_name='kineticmodel',
            name='transport',
            field=models.ManyToManyField(blank=True, to='kineticmodels.Transport'),
        ),
        migrations.AddField(
            model_name='isomer',
            name='species',
            field=models.ManyToManyField(to='kineticmodels.Species'),
        ),
        migrations.AddField(
            model_name='efficiency',
            name='kinetics_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.BaseKineticsData'),
        ),
        migrations.AddField(
            model_name='efficiency',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Species'),
        ),
        migrations.AddField(
            model_name='basekineticsdata',
            name='collider_efficiencies',
            field=models.ManyToManyField(blank=True, through='kineticmodels.Efficiency', to='kineticmodels.Species'),
        ),
        migrations.AddField(
            model_name='basekineticsdata',
            name='kinetics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Kinetics'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Source'),
        ),
        migrations.AlterUniqueTogether(
            name='stoichiometry',
            unique_together=set([('species', 'reaction', 'stoichiometry')]),
        ),
        migrations.AddField(
            model_name='pressure',
            name='arrhenius',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Arrhenius'),
        ),
        migrations.AddField(
            model_name='pressure',
            name='pdep_arrhenius',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.PDepArrhenius'),
        ),
        migrations.AddField(
            model_name='pdeparrhenius',
            name='arrhenius_set',
            field=models.ManyToManyField(through='kineticmodels.Pressure', to='kineticmodels.Arrhenius'),
        ),
        migrations.AddField(
            model_name='multipdeparrhenius',
            name='pdep_arrhenius_set',
            field=models.ManyToManyField(to='kineticmodels.PDepArrhenius'),
        ),
    ]
