# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kineticmodels', '0033_arrheniuskinetics_kinetics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrheniuskinetics',
            name='relative_uncertainty',
        ),
        migrations.AddField(
            model_name='kinetics',
            name='relative_uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
