# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kineticmodels', '0035_auto_20160622_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kineticmodel',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Source'),
        ),
    ]
