# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kineticmodels', '0036_auto_20160622_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrheniuskinetics',
            name='E_value',
            field=models.FloatField(default=0.0),
        ),
    ]
