# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kineticmodels', '0037_auto_20160623_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='kinetics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Kinetics'),
        ),
        migrations.AlterField(
            model_name='kineticmodel',
            name='kinetics',
            field=models.ManyToManyField(through='kineticmodels.Comment', to='kineticmodels.Kinetics'),
        ),
    ]
