# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import kineticmodels.models


class Migration(migrations.Migration):

    dependencies = [
        ('kineticmodels', '0040_auto_20160623_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kineticmodel',
            name='chemkin_reactions_file',
            field=models.FileField(blank=True, upload_to=kineticmodels.models.kinetic_model.upload_chemkin_to),
        ),
        migrations.AlterField(
            model_name='kineticmodel',
            name='chemkin_thermo_file',
            field=models.FileField(blank=True, upload_to=kineticmodels.models.kinetic_model.upload_thermo_to),
        ),
        migrations.AlterField(
            model_name='kineticmodel',
            name='chemkin_transport_file',
            field=models.FileField(blank=True, upload_to=kineticmodels.models.kinetic_model.upload_transport_to),
        ),
        migrations.AlterField(
            model_name='source',
            name='bPrimeID',
            field=models.CharField(blank=True, default=b'', max_length=9, verbose_name=b'Prime ID'),
        ),
    ]
