# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kineticmodels', '0041_auto_20160630_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kineticmodel',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Source'),
        ),
    ]
