# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kineticmodels', '0042_auto_20160707_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kineticmodel',
            name='additional_info',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='kineticmodel',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Source'),
        ),
    ]
