# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kineticmodels', '0043_auto_20160707_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kineticmodel',
            name='model_name',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True),
        ),
    ]
