# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import kineticmodels.models


class Migration(migrations.Migration):

    dependencies = [
        ('kineticmodels', '0044_auto_20160707_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kinetics',
            old_name='is_reverse',
            new_name='isReverse',
        ),
        migrations.AlterField(
            model_name='kineticmodel',
            name='chemkin_reactions_file',
            field=models.FileField(upload_to=kineticmodels.models.upload_chemkin_to),
        ),
        migrations.AlterField(
            model_name='kineticmodel',
            name='chemkin_thermo_file',
            field=models.FileField(upload_to=kineticmodels.models.upload_thermo_to),
        ),
        migrations.AlterField(
            model_name='source',
            name='authors',
            field=models.ManyToManyField(blank=True, through='kineticmodels.Authorship', to='kineticmodels.Author'),
        ),
        migrations.AlterField(
            model_name='source',
            name='publication_year',
            field=models.CharField(blank=True, default=b'', max_length=4, verbose_name=b'Year of Publication'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_title',
            field=models.CharField(blank=True, default=b'', max_length=300),
        ),
    ]
