# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kineticmodels', '0047_auto_20160811_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kinetics',
            old_name='relative_uncertainty',
            new_name='relativeUncertainty',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='is_reversible',
            new_name='isReversible',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='rotational_relaxation',
            new_name='rotationalRelaxation',
        ),
    ]
