# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kineticmodels', '0048_auto_20160811_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrheniuskinetics',
            old_name='A_value',
            new_name='AValue',
        ),
        migrations.RenameField(
            model_name='arrheniuskinetics',
            old_name='A_value_uncertainty',
            new_name='AValueUncertainty',
        ),
        migrations.RenameField(
            model_name='arrheniuskinetics',
            old_name='E_value',
            new_name='EValue',
        ),
        migrations.RenameField(
            model_name='arrheniuskinetics',
            old_name='E_value_uncertainty',
            new_name='EValueUncertainty',
        ),
        migrations.RenameField(
            model_name='arrheniuskinetics',
            old_name='lower_temp_bound',
            new_name='lowerTempBound',
        ),
        migrations.RenameField(
            model_name='arrheniuskinetics',
            old_name='n_value',
            new_name='nValue',
        ),
        migrations.RenameField(
            model_name='arrheniuskinetics',
            old_name='upper_temp_bound',
            new_name='upperTempBound',
        ),
    ]
