# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kineticmodels', '0049_auto_20160811_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kineticmodel',
            old_name='model_name',
            new_name='modelName',
        ),    
        migrations.RenameField(
            model_name='kineticmodel',
            old_name='additional_info',
            new_name='additionalInfo',
        ),    
        migrations.RenameField(
            model_name='kineticmodel',
            old_name='chemkin_reactions_file',
            new_name='chemkinReactionsFile',
        ),    
        migrations.RenameField(
            model_name='kineticmodel',
            old_name='chemkin_thermo_file',
            new_name='chemkinThermoFile',
        ),    
        migrations.RenameField(
            model_name='kineticmodel',
            old_name='chemkin_transport_file',
            new_name='chemkinTransportFile',
        ),    
 
    ]
