# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kineticmodels', '0050_auto_20160811_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='publication_year',
            new_name='publicationYear',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='source_title',
            new_name='sourceTitle',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='journal_name',
            new_name='journalName',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='journal_volume_number',
            new_name='journalVolumeNumber',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='page_numbers',
            new_name='pageNumbers',
        ),

    ]
