# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kineticmodels', '0052_auto_20160811_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thermo',
            old_name='coefficient_1_1',
            new_name='coefficient11',
        ),
        migrations.RenameField(
            model_name='thermo',
            old_name='coefficient_2_1',
            new_name='coefficient21',
        ),
        migrations.RenameField(
            model_name='thermo',
            old_name='coefficient_3_1',
            new_name='coefficient31',
        ),
        migrations.RenameField(
            model_name='thermo',
            old_name='coefficient_4_1',
            new_name='coefficient41',
        ),
        migrations.RenameField(
            model_name='thermo',
            old_name='coefficient_5_1',
            new_name='coefficient51',
        ),
        migrations.RenameField(
            model_name='thermo',
            old_name='coefficient_6_1',
            new_name='coefficient61',
        ),
        migrations.RenameField(
            model_name='thermo',
            old_name='coefficient_7_1',
            new_name='coefficient71',
        ),
        migrations.RenameField(
            model_name='thermo',
            old_name='lower_temp_bound_1',
            new_name='lowerTempBound1',
        ),
        migrations.RenameField(
            model_name='thermo',
            old_name='reference_pressure',
            new_name='referencePressure',
        ),
        migrations.RenameField(
            model_name='thermo',
            old_name='reference_temperature',
            new_name='referenceTemperature',
        ),
        migrations.RenameField(
            model_name='thermo',
            old_name='upper_temp_bound_1',
            new_name='upperTempBound1',
        ),
    ]
