# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kineticmodels', '0053_auto_20160811_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thermo',
            old_name='coefficient_1_2',
            new_name='coefficient12',
        ),
        migrations.RenameField(
            model_name='thermo',
            old_name='coefficient_2_2',
            new_name='coefficient22',
        ),
        migrations.RenameField(
            model_name='thermo',
            old_name='coefficient_3_2',
            new_name='coefficient32',
        ),
        migrations.RenameField(
            model_name='thermo',
            old_name='coefficient_4_2',
            new_name='coefficient42',
        ),
        migrations.RenameField(
            model_name='thermo',
            old_name='coefficient_5_2',
            new_name='coefficient52',
        ),
        migrations.RenameField(
            model_name='thermo',
            old_name='coefficient_6_2',
            new_name='coefficient62',
        ),
        migrations.RenameField(
            model_name='thermo',
            old_name='coefficient_7_2',
            new_name='coefficient72',
        ),
        migrations.RenameField(
            model_name='thermo',
            old_name='lower_temp_bound_2',
            new_name='lowerTempBound2',
        ),
        migrations.RenameField(
            model_name='thermo',
            old_name='upper_temp_bound_2',
            new_name='upperTempBound2',
        ),
    ]
