# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-16 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kineticmodels', '0054_auto_20160811_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='rmg_import_path',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
