# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-23 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kineticmodels', '0055_source_rmg_import_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='kineticmodel',
            name='species',
            field=models.ManyToManyField(blank=True, through='kineticmodels.SpeciesName', to='kineticmodels.Species'),
        ),
        migrations.AddField(
            model_name='speciesname',
            name='kinetic_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.KineticModel'),
        ),
    ]
