# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-23 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kineticmodels', '0056_auto_20170323_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='rmg_import_path',
        ),
        migrations.AddField(
            model_name='kineticmodel',
            name='rmgImportPath',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
