# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kineticmodels', '0058_auto_20170323_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseKineticsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('min_pressure', models.FloatField()),
                ('max_pressure', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Efficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efficiency', models.FloatField()),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Species')),
            ],
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ArrheniusKinetics',
            new_name='Arrhenius',
        ),
        migrations.CreateModel(
            name='ArrheniusEP',
            fields=[
                ('basekineticsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kineticmodels.BaseKineticsData')),
                ('a', models.FloatField()),
                ('n', models.FloatField()),
                ('ep_alpha', models.FloatField()),
                ('e0', models.FloatField()),
            ],
            bases=('kineticmodels.basekineticsdata',),
        ),
        migrations.CreateModel(
            name='Chebyshev',
            fields=[
                ('basekineticsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kineticmodels.BaseKineticsData')),
                ('coefficient_matrix', models.TextField()),
                ('units', models.CharField(max_length=25)),
                ('inv_temp_terms', models.IntegerField()),
                ('log_pressure_terms', models.IntegerField()),
            ],
            bases=('kineticmodels.basekineticsdata',),
        ),
        migrations.CreateModel(
            name='KineticsData',
            fields=[
                ('basekineticsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kineticmodels.BaseKineticsData')),
                ('temp_array', models.TextField()),
                ('rate_coefficients', models.TextField()),
            ],
            bases=('kineticmodels.basekineticsdata',),
        ),
        migrations.CreateModel(
            name='Lindemann',
            fields=[
                ('basekineticsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kineticmodels.BaseKineticsData')),
                ('alpha', models.FloatField()),
                ('t1', models.FloatField()),
                ('t2', models.FloatField()),
                ('t3', models.FloatField()),
                ('chemical_species_efficiencies', models.ManyToManyField(through='kineticmodels.Efficiency', to='kineticmodels.Species')),
                ('high_arrhenius', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_lindemann', to='kineticmodels.Arrhenius')),
                ('low_arrhenius', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_lindemann', to='kineticmodels.Arrhenius')),
            ],
            bases=('kineticmodels.basekineticsdata',),
        ),
        migrations.CreateModel(
            name='MultiArrhenius',
            fields=[
                ('basekineticsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kineticmodels.BaseKineticsData')),
                ('arrheniuses', models.ManyToManyField(to='kineticmodels.Arrhenius')),
            ],
            bases=('kineticmodels.basekineticsdata',),
        ),
        migrations.CreateModel(
            name='MultiPDepArrhenius',
            fields=[
                ('basekineticsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kineticmodels.BaseKineticsData')),
            ],
            bases=('kineticmodels.basekineticsdata',),
        ),
        migrations.CreateModel(
            name='PDepArrhenius',
            fields=[
                ('basekineticsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kineticmodels.BaseKineticsData')),
            ],
            bases=('kineticmodels.basekineticsdata',),
        ),
        migrations.CreateModel(
            name='ThirdBody',
            fields=[
                ('basekineticsdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kineticmodels.BaseKineticsData')),
                ('chemical_species_efficiencies', models.ManyToManyField(through='kineticmodels.Efficiency', to='kineticmodels.Species')),
                ('low_arrhenius', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Arrhenius')),
            ],
            bases=('kineticmodels.basekineticsdata',),
        ),
        migrations.AddField(
            model_name='pressure',
            name='arrhenius',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Arrhenius'),
        ),
        migrations.AddField(
            model_name='basekineticsdata',
            name='kinetics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Kinetics'),
        ),
        migrations.AddField(
            model_name='pressure',
            name='pdep_arrhenius',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.PDepArrhenius'),
        ),
        migrations.AddField(
            model_name='pdeparrhenius',
            name='arrheniuses',
            field=models.ManyToManyField(through='kineticmodels.Pressure', to='kineticmodels.Arrhenius'),
        ),
        migrations.AddField(
            model_name='pdeparrhenius',
            name='chemical_species_efficiencies',
            field=models.ManyToManyField(through='kineticmodels.Efficiency', to='kineticmodels.Species'),
        ),
        migrations.AddField(
            model_name='multipdeparrhenius',
            name='pdep_arrheniuses',
            field=models.ManyToManyField(to='kineticmodels.PDepArrhenius'),
        ),
        migrations.AddField(
            model_name='efficiency',
            name='lindemann',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.Lindemann'),
        ),
        migrations.AddField(
            model_name='efficiency',
            name='pdep_arrhenius',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.PDepArrhenius'),
        ),
        migrations.AddField(
            model_name='efficiency',
            name='third_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kineticmodels.ThirdBody'),
        ),
    ]
