name: Docker Builds
on:
  push:
    branches: [ master ]
jobs:
  docker_builds:
    name: Docker Builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
      - uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout RMG-models
      - uses: actions/checkout@v2
        with:
          repository: comocheng/RMG-models
          token: ${{ secrets.PAT }}
          path: rmg-models
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build RMG Image
        uses: docker/build-push-action@v2
        with:
          file: main/Dockerfile.rmg
          push: true
          tags: comocheng/kms-rmg:latest
      - name: Build Application Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: comocheng/kms:latest
