name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, ready_for_review ]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: docker-compose run web ./bin/test.sh --rm
