name: Run Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: kms_env
          environment-file: environment.yml
          python-version: 3.7
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          python manage.py test
